version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - NODE_ENV=development
      - DB_HOST=docker_db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=Herbertpur@3
      - DB_NAME=test
    depends_on:
      - docker_db

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app
    depends_on:
      - backend

  docker_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Herbertpur@3
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
